### ISSUE TITLE
RFC Etiquette - missing end of sentence

### ISSUE THREAD

**Issue by dochne** [Danack/RfcCodex#4]
Line 28 is missing the end of the sentence:

`While that sounds reasonable on the surface, the amount of time people have to work on PHP RFCs is often limited. Having someone tell you "thanks for volunteering, but now I want you to do a lot more work than you volunteered for" is subtle way o`

I'd PR a fix but I'm honestly not sure what the end of the sentence was going to be.

Thanks for creating this resource!

**Comment by Danack** [comment]
Yeah, I was trying not to swear, which lead me to run out of vocabulary....

I've put words as:

> While that sounds reasonable on the surface, the amount of time people have to work on PHP RFCs is often limited. Having someone say "thanks for volunteering, but now I want you to do a lot more work than you volunteered for" is a subtle way of preventing RFCs from being implemented.
>
>In some cases the suggestion to make the RFC be bigger has been well-intentioned, and so the damage has been accidental.
>
>In other cases, it would seem that the suggestion that the RFC needs to be a lot bigger or not done at all has come from someone who doesn't want the RFC to pass, which could be interpreted as deliberately making it more difficult for the RFC to pass. 
>
>It's okay for RFCs to be small in scope, so long as they are self-contained.
