### ISSUE TITLE
Missing end of sentence at core_library.md

### ISSUE THREAD

**Issue by mmarton** [Danack/RfcCodex#8]
In the end of forecast block
https://github.com/Danack/RfcCodex/blob/master/standardise_core_library.md#forecast
> It's much more likely that an alternative approach, such as improving PHP with scalar objects would take the language to

Nice repo btw, found it on:
https://blog.jetbrains.com/phpstorm/2019/03/php-annotated-monthly-march-2019/

**Comment by Danack** [comment]
Thanks...I probably ought to try to avoid doing that.
